"""Enhanced Task and User models

Revision ID: ae1604e2afda
Revises: 88f07a402de9
Create Date: 2024-10-31 13:51:04.109436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1604e2afda'
down_revision = '88f07a402de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('task_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        # Naming the foreign key constraint
        batch_op.create_foreign_key('fk_task_assignee', 'user', ['assignee_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('task', schema=None) as batch_op:
        # Naming the foreign key constraint to drop it
        batch_op.drop_constraint('fk_task_assignee', type_='foreignkey')
        batch_op.drop_column('assignee_id')
        batch_op.drop_column('task_type')
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###